swagger: '2.0'
info:
  description: This is a sample server of ACME Explorer Application.
  version: 1.0.0
  title: ACME EXPLORER
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: acme.explorer.io
basePath: /v1
schemes:
  - https
  - http
paths:
  /actors:
    get:
      tags:
        - Actor
      summary: Return all actors
      description: ''
      operationId: list_all_actors
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Actor
    post:
      tags:
        - Actor
      summary: Add a new actor
      description: ''
      operationId: create_an_actor
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Actor object that needs to be added to the Acme Explorer
          required: true
          schema:
            $ref: '#/definitions/Actor'
      responses:
        '405':
          description: Invalid input
      x-swagger-router-controller: Actor
  /actors/{actorId}:
    get:
      tags:
        - Actor
      summary: Find actor by ID
      description: Returns a single actor
      operationId: read_an_actor
      produces:
        - application/xml
        - application/json
      parameters:
        - name: actorId
          in: path
          description: ID of actor to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Actor'
        '400':
          description: Invalid ID supplied
        '404':
          description: Actor not found
      x-swagger-router-controller: Actor
    put:
      tags:
        - Actor
      summary: Update actor
      description: This can only be done by the logged in user.
      operationId: update_an_actor
      produces:
        - application/xml
        - application/json
      parameters:
        - name: actorId
          in: path
          description: Actor ID that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated actor object
          required: true
          schema:
            $ref: '#/definitions/Actor'
      responses:
        '400':
          description: Invalid actor ID supplied
        '404':
          description: Actor not found
      x-swagger-router-controller: Actor
  /actors/{actorId}/ban:
    put:
      tags:
        - Actor
      summary: Ban an actor
      description: This can only be done by the logged in user.
      operationId: ban_an_actor
      produces:
        - application/xml
        - application/json
      parameters:
        - name: actorId
          in: path
          description: Ban an actor by ID
          required: true
          type: string
        - in: body
          name: body
          description: Ban an actor object
          required: true
          schema:
            $ref: '#/definitions/Actor'
      responses:
        '400':
          description: Invalid actor ID supplied
        '404':
          description: Actor not found
      x-swagger-router-controller: Actor
  /actors/{actorId}/unban:
    put:
      tags:
        - Actor
      summary: Unban an actor
      description: This can only be done by the logged in user.
      operationId: unban_an_actor
      produces:
        - application/xml
        - application/json
      parameters:
        - name: actorId
          in: path
          description: Unban an actor by ID
          required: true
          type: string
        - in: body
          name: body
          description: Unban an actor object
          required: true
          schema:
            $ref: '#/definitions/Actor'
      responses:
        '400':
          description: Invalid actor ID supplied
        '404':
          description: Actor not found
      x-swagger-router-controller: Actor    
  /trips:
    get:
      tags:
        - Trip
      summary: Return all trips
      description: ''
      operationId: list_all_trips
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Trips
    post:
      tags:
        - Trip
      summary: Add a new trip
      description: ''
      operationId: create_an_trip
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Trip object that needs to be added to the Acme Explorer
          required: true
          schema:
            $ref: '#/definitions/Trip'
      responses:
        '405':
          description: Invalid input
      x-swagger-router-controller: Trips
  /trips/search:
    get:
      tags:
        - Trip
      summary: Search trips
      description: ''
      operationId: trips.search_trips
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Trips
  /trips/{tripId}:
    get:
      tags:
        - Trip
      summary: Find trip by ID
      description: Returns a single trip
      operationId: read_a_trip
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Trip'
        '400':
          description: Invalid ID supplied
        '404':
          description: Trip not found
      x-swagger-router-controller: Trips
    put:
      tags:
        - Trip
      summary: Update a trip
      description: This can only be done by the authorized user.
      operationId: update_a_trip
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tripId
          in: path
          description: Trip ID that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated trip object
          required: true
          schema:
            $ref: '#/definitions/Trip'
      responses:
        '400':
          description: Invalid trip ID supplied
        '404':
          description: Trip not found
      x-swagger-router-controller: Trips
    delete:
      tags:
        - Trip
      summary: Deletes a trip
      description: ''
      operationId: delete_a_trip
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: tripId
          in: path
          description: Trip ID to delete
          required: true
          type: string
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Trip not found
      x-swagger-router-controller: Trips
  /applications:
    get:
      tags:
        - Application
      summary: Return list of all applications
      description: ''
      operationId: list_all_applications
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Applications
    post:
      tags:
        - Application
      summary: Add a new application
      description: ''
      operationId: create_an_application
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Application object that needs to be added to the Acme Explorer
          required: true
          schema:
            $ref: '#/definitions/Application'
      responses:
        '405':
          description: Invalid input
      x-swagger-router-controller: Applications
  /applications/applicationId/changeStatus:
    get:
      tags:
        - Application
      summary: Find application by Application ID
      description: Returns a application by Application ID
      operationId: search_user_applications
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return by its application
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Application'
        '400':
          description: Invalid ID supplied
        '404':
          description: Application not found
      x-swagger-router-controller: Applications
  /applications/{applicationId}:
    get:
      tags:
        - Application
      summary: Find application by applicationId
      description: Returns an application by applicationId
      operationId: read_an_application
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return an application
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Application'
        '400':
          description: Invalid ID supplied
        '404':
          description: Application not found
      x-swagger-router-controller: Applications
    put:
      tags:
        - Application
      summary: Update an Application
      description: This can only be done by the authorized actor.
      operationId: update_an_application
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationId
          in: path
          description: Application ID that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated trip object
          required: true
          schema:
            $ref: '#/definitions/Application'
      responses:
        '400':
          description: Invalid trip ID supplied
        '404':
          description: Application not found
      x-swagger-router-controller: Applications
  /sponsorships:
    get:
      tags:
        - Sponsorship
      summary: Return all sponsorships
      description: ''
      operationId: list_all_sponsorships
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Sponsorships
    post:
      tags:
        - Sponsorship
      summary: Add a new sponsorship
      description: ''
      operationId: create_a_sponsorship
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Sponsorship object that needs to be added to the Acme Explorer
          required: true
          schema:
            $ref: '#/definitions/Trip'
      responses:
        '405':
          description: Invalid input
      x-swagger-router-controller: Trips
  /sponsorships/{sponsorshipId}:
    get:
      tags:
        - Sponsorship
      summary: Find sponsorship by ID
      description: Returns a single sponsorship
      operationId: read_a_sponsorship
      produces:
        - application/xml
        - application/json
      parameters:
        - name: sponsorshipId
          in: path
          description: ID of sponsorship to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Sponsorship'
        '400':
          description: Invalid ID supplied
        '404':
          description: Sponsorship not found
      x-swagger-router-controller: Sponsorships
    put:
      tags:
        - Sponsorship
      summary: Update a sponsorship
      description: This can only be done by the authorized user.
      operationId: update_a_sponsorship
      produces:
        - application/xml
        - application/json
      parameters:
        - name: sponsorshipId
          in: path
          description: sponsorshipId that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Update sponsorship object
          required: true
          schema:
            $ref: '#/definitions/Sponsorship'
      responses:
        '400':
          description: Invalid sponsorship ID supplied
        '404':
          description: Sponsorship not found
      x-swagger-router-controller: Sponsorships
    delete:
      tags:
        - Sponsorship
      summary: Delete a sponsorship
      description: ''
      operationId: delete_a_sponsorship
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: sponsorshipId
          in: path
          description: Sponsorship ID to delete
          required: true
          type: string
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Sponsorship not found
      x-swagger-router-controller: Sponsorships
  /finders:
    get:
      tags:
        - Finder
      summary: Return all finders
      description: ''
      operationId: list_all_finders
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Finder
    post:
      tags:
        - Finder
      summary: Add a new finder
      description: ''
      operationId: create_an_finder
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Finder object that needs to be added to the Acme Explorer
          required: true
          schema:
            $ref: '#/definitions/Finder'
      responses:
        '405':
          description: Invalid input
      x-swagger-router-controller: Finder
  /finders/{explorerId}:
    get:
      tags:
        - Finder
      summary: Find search criteria by Explorer ID
      description: Returns a search criteria by Explorer ID
      operationId: search_explorer_criteria
      produces:
        - application/xml
        - application/json
      parameters:
        - name: explorerId
          in: path
          description: ID of explorer to return by its criteria
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Finder'
        '400':
          description: Invalid ID supplied
        '404':
          description: Finder not found
      x-swagger-router-controller: Finder
    put:
      tags:
        - Finder
      summary: Update a search criteria
      description: This can only be done by the authorized user.
      operationId: update_finder
      produces:
        - application/xml
        - application/json
      parameters:
        - name: explorerId
          in: path
          description: explorerId that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Update finder object
          required: true
          schema:
            $ref: '#/definitions/Finder'
      responses:
        '400':
          description: Invalid explorer ID supplied
        '404':
          description: Finder not found
      x-swagger-router-controller: Finder
  /datawarehouse:
    get:
      tags:
        - Datawarehouse
      summary: Return all indicators
      description: ''
      operationId: list_all_indicators
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Datawarehouse
    post:
      tags:
        - Datawarehouse
      summary: Create a new computation period for rebuilding
      description: ''
      operationId: rebuildPeriod
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: New computation object that needs to be added to the Acme Explorer
          required: true
          schema:
            $ref: '#/definitions/Trip'
      responses:
        '405':
          description: Invalid input
      x-swagger-router-controller: Datawarehouse
  /datawarehouse/latest:
    get:
      tags:
        - Datawarehouse
      summary: Get list of last computed indicator
      description: Get list of last computed indicator
      operationId: dataWareHouse.last_indicator
      produces:
        - application/xml
        - application/json
      parameters:
        - name: latest
          in: path
          description: list of last indicator computed
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Datawarehouse'
        '400':
          description: Invalid indicator supplied
        '404':
          description: Indicator not found
      x-swagger-router-controller: Datawarehouse
definitions:
  Actor:
    type: object
    required:
      - address
      - banned
      - created
      - email
      - name
      - password
      - phone
      - preferredLanguage
      - role
      - search
      - surname
    properties:
      name:
        type: string
      surname:
        type: string
      email:
        type: string
        minLength: 1
      phone:
        type: string
        minLength: 1
      address:
        type: string
      password:
        type: string
        minLength: 1
      preferredLanguage:
        type: string
        minLength: 1
      role:
        type: number
      banned:
        type: boolean
      search:
        type: object
        properties: {}
      created:
        type: string
        format: date
    example:
      password: password
      preferredLanguage: preferredLanguage
      search: '{}'
      address: address
      role: 0.8008281904610115
      phone: phone
      surname: surname
      created: '2000-01-23'
      name: name
      banned: true
      email: email
  Application:
    type: object
    required:
      - cancelationMoment
      - comments
      - consumerName
      - dateApplication
      - datePayment
      - explorerId
      - managerId
      - status
      - tripId
    properties:
      status:
        type: string
      consumerName:
        type: string
      dateApplication:
        type: string
        format: date
      datePayment:
        type: string
        format: date
      cancelationMoment:
        type: string
        format: date
      comments:
        type: number
      explorerId:
        type: object
        properties: {}
      tripId:
        type: object
        properties: {}
      managerId:
        type: object
        properties: {}
    example:
      cancelationMoment: '2000-01-23'
      dateApplication: '2000-01-23'
      comments: 0.8008281904610115
      trip: '{}'
      manager: '{}'
      explorer: '{}'
      status: status
      consumerName: consumerName
      datePayment: '2000-01-23'
  Trip:
    type: object
    required:
      - comments
      - created
      - dateEnd
      - dateInit
      - description
      - list_of_applications
      - pictures
      - price
      - sponsors
      - stages
      - ticker
      - title
    properties:
      ticker:
        type: string
      title:
        type: string
      description:
        type: string
      price:
        type: number
      list_of_applications:
        type: object
        properties: {}
      dateInit:
        type: string
        format: date
      dateEnd:
        type: string
        format: date
      pictures:
        type: object
        properties: {}
      stages:
        type: object
        properties: {}
      comments:
        type: object
        properties: {}
      sponsors:
        type: object
        properties: {}
      created:
        type: string
        format: date
    example:
      ticker: ticker
      list_of_applications: '{}'
      comments: '{}'
      price: 0.8008281904610115
      sponsors: '{}'
      created: '2000-01-23'
      dateInit: '2000-01-23'
      stages: '{}'
      description: description
      dateEnd: '2000-01-23'
      title: title
      pictures: '{}'
  Sponsorship:
    type: object
    required:
      - banner
      - link
      - paid
      - price
      - sponsorId
      - tripId
    properties:
      banner:
        type: object
        properties: {}
      link:
        type: string
      paid:
        type: boolean
      price:
        type: number
      sponsorId:
        type: number
      tripId:
        type: number
    example:
      banner: {}
      link: acmerexplorer.swagger.io
      paid: true
      price: 654121
      sponsordID: 4238795
      tripId: 51238
  Finder:
    type: object
    required:
      - keyword
      - priceMin
      - priceMax
      - dateInit
      - dateEnd
      - explorerId
    properties:
      keyword:
        type: string
      priceMin:
        type: number
      priceMax:
        type: number
      dateInit:
        type: string
        format: datetime
      dateEnd:
        type: string
        format: datetime
      explorerId:
        type: number
    example:
      keyword: paris
      priceMin: 0
      priceMax: 644646
      dateInit: 2019-04-16
      dateEnd: 2019-04-20
      explorerId: 52
  Datawarehouse:
    type: object
    required:
      - tripsManagerStats
      - applicationsTripStats
      - priceTripStats
      - applicationsRatioPerStatus
      - averagePriceFinderStats
      - topKeywordsFinderStats
    properties:
      tripsManagerStats:
        type: object
        properties: {}
      applicationsTripStats:
        type: object
        properties: {}
      priceTripStats:
        type: object
        properties: {}
      applicationsRatioPerStatus:
        type: object
        properties: {}
      averagePriceFinderStats:
        type: object
        properties: {}
      topKeywordsFinderStats:
        type: object
        properties: {}